config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :planets, only: [:index, :show, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
    has_many :planets
end

app/models/planet.rb
class Planet < ApplicationRecord
    belongs_to :galaxy
    validates :name, uniqueness: true, presence: true
    def self.by_position
        order(:position)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
    def index
        @ordered_planets = Planet.by_position
    end
    def show
        @planet = Planet.find(params[:id])
    end
    def new
        @planet = Planet.new
    end
    def create
        @planet = Planet.create(planet_params)
        if @planet.save
        redirect_to planets_path
        else
            render :new
        end
    end
    private
    def planet_params
        params.require(:planet).permit(:name, :info, :galaxy_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/index.html.erb
<h1>Planets</h1>

<div>
    <% @ordered_planets.each do |planet| %>
        <h3>Position: <%= planet.position %></h3>
        <p>Name: <%= link_to planet.name, planet_path(planet) %></p>
        <p>Galaxy: <%= planet.galaxy.name %></p>
        <p>Info: <%= planet.info %></p>
        <p><%= "Has Rings!" if planet.has_rings %></p>
    <% end %>
</div>

<%= link_to "Create new Planet", new_planet_path %>

app/views/planets/new.html.erb
<h1>New Planet</h1>
<% if @planet.errors.any? %>
    <%= "Error!" %>
<% end %>
<%= form_for @planet do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :info %>
    <%= f.text_area :info %>
    <%= f.label :galaxy %>
    <%= f.collection_select :galaxy_id, Galaxy.all, :id, :name %>
    <%= f.submit "Add the Planet" %>
<% end %>

app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>

<h3> Position: <%= @planet.position %></h3>
<div>
    <p>Name: <%= @planet.name %></p>
    <p>Info: <%= @planet.info %></p>
    <p><%= "Has Rings!" if @planet.has_rings %></p>
</div>